name: Link Check
on:
  push:
    branches: [main]
  pull_request:
    paths:
      - '**/*.md'
      - '.github/workflows/link-check.yml'

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7

      - name: Restore lychee cache
        uses: actions/cache@v5
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      - name: Link Checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: >-
            --no-progress
            --verbose
            --include-fragments
            './**/*.md'
          fail: true